
# lib_build
LIB_MAKE += $(ECOS_PROJECT_DIR)/lib/common

# apps_build
APPS_MAKE += $(ECOS_PROJECT_DIR)/apps/ecos
APPS_MAKE += $(ECOS_PROJECT_DIR)/apps/test

# modules_build
MODULES_MAKE += $(ECOS_PROJECT_DIR)/modules/ecos_gpio

